# 应用名称
spring:
  redis:
    host: 192.168.1.10
    port: 6379
  profiles:
    active: dev
  # 数据库驱动：
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
      # 数据库连接地址
    url: jdbc:mysql://localhost:3311/mybatis_plus?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    # 数据库用户名&密码：
    username: root
    password: 123456
# 应用服务 WEB 访问端口
server:
  port: 8080
#下面这些内容是为了让MyBatis映射
#mybatis:
#  #指定Mybatis的Mapper文件
#  mapper-locations: classpath:mappers/*xml
#  #指定Mybatis的实体目录
#  type-aliases-package: com.horsefarmer.springboottool.entity
logging:
  config: classpath:config/log4j2-spring.xml
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)